-- MySQL Script generated by MySQL Workbench
-- Sat Oct 23 22:29:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chihuahua
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chihuahua
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chihuahua` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `chihuahua` ;

-- -----------------------------------------------------
-- Table `chihuahua`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chihuahua`.`USER` ;

CREATE TABLE IF NOT EXISTS `chihuahua`.`USER` (
    `USER_ID` BIGINT UNSIGNED NULL AUTO_INCREMENT,
    `USER_NAME` VARCHAR(100) NOT NULL,
    `HASH_PASS` VARCHAR(100) NOT NULL,
    `EMAIL` VARCHAR(100) NOT NULL,
    `LOCATION` VARCHAR(50) NULL,
    `DELETE_FLG` TINYINT NOT NULL,
    `VERSION` INT NOT NULL DEFAULT 0,
    `CREATED_DATETIME` DATETIME NOT NULL,
    `UPDATED_DATETIME` DATETIME NOT NULL,
    PRIMARY KEY (`USER_ID`),
    UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chihuahua`.`DOG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chihuahua`.`DOG` ;

CREATE TABLE IF NOT EXISTS `chihuahua`.`DOG` (
    `DOG_ID` BIGINT UNSIGNED NULL AUTO_INCREMENT,
    `DOG_NAME` VARCHAR(100) NOT NULL,
    `GENDER_TYPE` VARCHAR(10) NOT NULL,
    `BIRTH_DATE` DATE NOT NULL,
    `USER_USER_ID` BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (`DOG_ID`),
    INDEX `fk_DOG_USER_idx` (`USER_USER_ID` ASC) VISIBLE,
    CONSTRAINT `fk_DOG_USER`
    FOREIGN KEY (`USER_USER_ID`)
    REFERENCES `chihuahua`.`USER` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
