-- create tables
DROP TABLE IF EXISTS USER;

CREATE TABLE IF NOT EXISTS USER (
    USER_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    USER_NAME VARCHAR(100) NOT NULL,
    HASH_PASS VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    LOCATION VARCHAR(50) NULL,
    DELETE_FLG TINYINT NOT NULL,
    VERSION INT NOT NULL DEFAULT 0,
    CREATED_DATETIME DATETIME  NOT NULL,
    UPDATED_DATETIME DATETIME  NOT NULL,
    PRIMARY KEY (USER_ID)
);

DROP TABLE IF EXISTS DOG;
    
CREATE TABLE IF NOT EXISTS DOG (
    DOG_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    USER_ID BIGINT UNSIGNED NOT NULL,
    DOG_NAME VARCHAR(100) NOT NULL,
    GENDER_TYPE VARCHAR(10) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    VERSION INT NOT NULL DEFAULT 0,
    CREATED_DATETIME DATETIME NOT NULL,
    UPDATED_DATETIME DATETIME NOT NULL,
    PRIMARY KEY (DOG_ID)
);

-- create foreign ey index
ALTER TABLE DOG
    ADD CONSTRAINT FK_DOG_USER FOREIGN KEY (USER_ID)
        REFERENCES USER (USER_ID)
        ON UPDATE RESTRICT
        ON DELETE RESTRICT
;
