-- USER
INSERT INTO USER (USER_ID, USER_NAME, HASH_PASS, EMAIL, LOCATION, DELETE_FLG, VERSION, CREATED_DATETIME, UPDATED_DATETIME) VALUES (1, 'sora', 'aaa', 'sora@example.com', 'Tokyo', 0, 0, now(), now());

-- DOG
INSERT INTO DOG (DOG_ID, USER_ID, DOG_NAME, GENDER_TYPE, BIRTH_DATE, VERSION, CREATED_DATETIME, UPDATED_DATETIME) VALUES (1, 1, 'mao', 'FEMALE', '2021-01-25', 0, now(), now());
